// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: catalog.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCourses = `-- name: CountCourses :one
SELECT COUNT(*)
FROM course_catalog
WHERE ($1::text IS NULL OR faculty = $1)
  AND ($2::text IS NULL OR department = $2)
  AND ($3::course_type_enum IS NULL OR course_type = $3)
  AND ($4::course_catalog_status_enum IS NULL OR status = $4)
  AND ($5::SMALLINT IS NULL OR class_level = $5)
  AND ($6::text IS NULL OR name ILIKE '%' || $6 || '%' OR course_code ILIKE '%' || $6 || '%')
`

type CountCoursesParams struct {
	Faculty    pgtype.Text                 `json:"faculty"`
	Department pgtype.Text                 `json:"department"`
	CourseType NullCourseTypeEnum          `json:"course_type"`
	Status     NullCourseCatalogStatusEnum `json:"status"`
	ClassLevel pgtype.Int2                 `json:"class_level"`
	Search     pgtype.Text                 `json:"search"`
}

func (q *Queries) CountCourses(ctx context.Context, arg CountCoursesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCourses,
		arg.Faculty,
		arg.Department,
		arg.CourseType,
		arg.Status,
		arg.ClassLevel,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCourse = `-- name: CreateCourse :one
INSERT INTO course_catalog (
    course_code, name, faculty, department, class_level, credits,
    theoretical_hours, practical_hours, course_type, prerequisites,
    description, learning_outcomes, syllabus, status
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, course_code, name, faculty, department, class_level, credits,
          theoretical_hours, practical_hours, course_type, prerequisites,
          description, learning_outcomes, syllabus, status, created_at, updated_at
`

type CreateCourseParams struct {
	CourseCode       string                      `json:"course_code"`
	Name             string                      `json:"name"`
	Faculty          string                      `json:"faculty"`
	Department       string                      `json:"department"`
	ClassLevel       int16                       `json:"class_level"`
	Credits          int16                       `json:"credits"`
	TheoreticalHours int16                       `json:"theoretical_hours"`
	PracticalHours   int16                       `json:"practical_hours"`
	CourseType       CourseTypeEnum              `json:"course_type"`
	Prerequisites    []byte                      `json:"prerequisites"`
	Description      pgtype.Text                 `json:"description"`
	LearningOutcomes pgtype.Text                 `json:"learning_outcomes"`
	Syllabus         pgtype.Text                 `json:"syllabus"`
	Status           NullCourseCatalogStatusEnum `json:"status"`
}

func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) (CourseCatalog, error) {
	row := q.db.QueryRow(ctx, createCourse,
		arg.CourseCode,
		arg.Name,
		arg.Faculty,
		arg.Department,
		arg.ClassLevel,
		arg.Credits,
		arg.TheoreticalHours,
		arg.PracticalHours,
		arg.CourseType,
		arg.Prerequisites,
		arg.Description,
		arg.LearningOutcomes,
		arg.Syllabus,
		arg.Status,
	)
	var i CourseCatalog
	err := row.Scan(
		&i.ID,
		&i.CourseCode,
		&i.Name,
		&i.Faculty,
		&i.Department,
		&i.ClassLevel,
		&i.Credits,
		&i.TheoreticalHours,
		&i.PracticalHours,
		&i.CourseType,
		&i.Prerequisites,
		&i.Description,
		&i.LearningOutcomes,
		&i.Syllabus,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCourseByCourseCode = `-- name: GetCourseByCourseCode :one
SELECT id, course_code, name, faculty, department, class_level, credits,
       theoretical_hours, practical_hours, course_type, prerequisites,
       description, learning_outcomes, syllabus, status, created_at, updated_at
FROM course_catalog
WHERE course_code = $1
LIMIT 1
`

func (q *Queries) GetCourseByCourseCode(ctx context.Context, courseCode string) (CourseCatalog, error) {
	row := q.db.QueryRow(ctx, getCourseByCourseCode, courseCode)
	var i CourseCatalog
	err := row.Scan(
		&i.ID,
		&i.CourseCode,
		&i.Name,
		&i.Faculty,
		&i.Department,
		&i.ClassLevel,
		&i.Credits,
		&i.TheoreticalHours,
		&i.PracticalHours,
		&i.CourseType,
		&i.Prerequisites,
		&i.Description,
		&i.LearningOutcomes,
		&i.Syllabus,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCourseByID = `-- name: GetCourseByID :one
SELECT id, course_code, name, faculty, department, class_level, credits,
       theoretical_hours, practical_hours, course_type, prerequisites,
       description, learning_outcomes, syllabus, status, created_at, updated_at
FROM course_catalog
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetCourseByID(ctx context.Context, id pgtype.UUID) (CourseCatalog, error) {
	row := q.db.QueryRow(ctx, getCourseByID, id)
	var i CourseCatalog
	err := row.Scan(
		&i.ID,
		&i.CourseCode,
		&i.Name,
		&i.Faculty,
		&i.Department,
		&i.ClassLevel,
		&i.Credits,
		&i.TheoreticalHours,
		&i.PracticalHours,
		&i.CourseType,
		&i.Prerequisites,
		&i.Description,
		&i.LearningOutcomes,
		&i.Syllabus,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCoursesByIDs = `-- name: GetCoursesByIDs :many
SELECT id, course_code, name, class_level
FROM course_catalog
WHERE id = ANY($1::uuid[])
`

type GetCoursesByIDsRow struct {
	ID         pgtype.UUID `json:"id"`
	CourseCode string      `json:"course_code"`
	Name       string      `json:"name"`
	ClassLevel int16       `json:"class_level"`
}

func (q *Queries) GetCoursesByIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]GetCoursesByIDsRow, error) {
	rows, err := q.db.Query(ctx, getCoursesByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCoursesByIDsRow{}
	for rows.Next() {
		var i GetCoursesByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.CourseCode,
			&i.Name,
			&i.ClassLevel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCourses = `-- name: ListCourses :many
SELECT id, course_code, name, faculty, department, class_level, credits,
       theoretical_hours, practical_hours, course_type, prerequisites, status
FROM course_catalog
WHERE ($1::text IS NULL OR faculty = $1)
  AND ($2::text IS NULL OR department = $2)
  AND ($3::course_type_enum IS NULL OR course_type = $3)
  AND ($4::course_catalog_status_enum IS NULL OR status = $4)
  AND ($5::SMALLINT IS NULL OR class_level = $5)
  AND ($6::text IS NULL OR name ILIKE '%' || $6 || '%' OR course_code ILIKE '%' || $6 || '%')
ORDER BY course_code
LIMIT $8 OFFSET $7
`

type ListCoursesParams struct {
	Faculty    pgtype.Text                 `json:"faculty"`
	Department pgtype.Text                 `json:"department"`
	CourseType NullCourseTypeEnum          `json:"course_type"`
	Status     NullCourseCatalogStatusEnum `json:"status"`
	ClassLevel pgtype.Int2                 `json:"class_level"`
	Search     pgtype.Text                 `json:"search"`
	Offset     int32                       `json:"offset"`
	Limit      int32                       `json:"limit"`
}

type ListCoursesRow struct {
	ID               pgtype.UUID                 `json:"id"`
	CourseCode       string                      `json:"course_code"`
	Name             string                      `json:"name"`
	Faculty          string                      `json:"faculty"`
	Department       string                      `json:"department"`
	ClassLevel       int16                       `json:"class_level"`
	Credits          int16                       `json:"credits"`
	TheoreticalHours int16                       `json:"theoretical_hours"`
	PracticalHours   int16                       `json:"practical_hours"`
	CourseType       CourseTypeEnum              `json:"course_type"`
	Prerequisites    []byte                      `json:"prerequisites"`
	Status           NullCourseCatalogStatusEnum `json:"status"`
}

func (q *Queries) ListCourses(ctx context.Context, arg ListCoursesParams) ([]ListCoursesRow, error) {
	rows, err := q.db.Query(ctx, listCourses,
		arg.Faculty,
		arg.Department,
		arg.CourseType,
		arg.Status,
		arg.ClassLevel,
		arg.Search,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCoursesRow{}
	for rows.Next() {
		var i ListCoursesRow
		if err := rows.Scan(
			&i.ID,
			&i.CourseCode,
			&i.Name,
			&i.Faculty,
			&i.Department,
			&i.ClassLevel,
			&i.Credits,
			&i.TheoreticalHours,
			&i.PracticalHours,
			&i.CourseType,
			&i.Prerequisites,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCourse = `-- name: UpdateCourse :one
UPDATE course_catalog
SET name = COALESCE($2, name),
    faculty = COALESCE($3, faculty),
    department = COALESCE($4, department),
    class_level = COALESCE($5, class_level),
    credits = COALESCE($6, credits),
    theoretical_hours = COALESCE($7, theoretical_hours),
    practical_hours = COALESCE($8, practical_hours),
    course_type = COALESCE($9, course_type),
    prerequisites = COALESCE($10, prerequisites),
    description = COALESCE($11, description),
    learning_outcomes = COALESCE($12, learning_outcomes),
    syllabus = COALESCE($13, syllabus),
    status = COALESCE($14, status),
    updated_at = NOW()
WHERE course_code = $1
RETURNING id, course_code, name, faculty, department, class_level, credits,
          theoretical_hours, practical_hours, course_type, prerequisites,
          description, learning_outcomes, syllabus, status, created_at, updated_at
`

type UpdateCourseParams struct {
	CourseCode       string                      `json:"course_code"`
	Name             pgtype.Text                 `json:"name"`
	Faculty          pgtype.Text                 `json:"faculty"`
	Department       pgtype.Text                 `json:"department"`
	ClassLevel       pgtype.Int2                 `json:"class_level"`
	Credits          pgtype.Int2                 `json:"credits"`
	TheoreticalHours pgtype.Int2                 `json:"theoretical_hours"`
	PracticalHours   pgtype.Int2                 `json:"practical_hours"`
	CourseType       NullCourseTypeEnum          `json:"course_type"`
	Prerequisites    []byte                      `json:"prerequisites"`
	Description      pgtype.Text                 `json:"description"`
	LearningOutcomes pgtype.Text                 `json:"learning_outcomes"`
	Syllabus         pgtype.Text                 `json:"syllabus"`
	Status           NullCourseCatalogStatusEnum `json:"status"`
}

func (q *Queries) UpdateCourse(ctx context.Context, arg UpdateCourseParams) (CourseCatalog, error) {
	row := q.db.QueryRow(ctx, updateCourse,
		arg.CourseCode,
		arg.Name,
		arg.Faculty,
		arg.Department,
		arg.ClassLevel,
		arg.Credits,
		arg.TheoreticalHours,
		arg.PracticalHours,
		arg.CourseType,
		arg.Prerequisites,
		arg.Description,
		arg.LearningOutcomes,
		arg.Syllabus,
		arg.Status,
	)
	var i CourseCatalog
	err := row.Scan(
		&i.ID,
		&i.CourseCode,
		&i.Name,
		&i.Faculty,
		&i.Department,
		&i.ClassLevel,
		&i.Credits,
		&i.TheoreticalHours,
		&i.PracticalHours,
		&i.CourseType,
		&i.Prerequisites,
		&i.Description,
		&i.LearningOutcomes,
		&i.Syllabus,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
