// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assessment_scores.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countScoresBySlugAndCourse = `-- name: CountScoresBySlugAndCourse :one
SELECT COUNT(DISTINCT sa.registration_id)
FROM student_assessment_scores sa
JOIN student_course_registrations r ON sa.registration_id = r.id
WHERE r.course_id = $1 AND sa.slug = $2
`

type CountScoresBySlugAndCourseParams struct {
	CourseID uuid.UUID `json:"course_id"`
	Slug     string    `json:"slug"`
}

func (q *Queries) CountScoresBySlugAndCourse(ctx context.Context, arg CountScoresBySlugAndCourseParams) (int64, error) {
	row := q.db.QueryRow(ctx, countScoresBySlugAndCourse, arg.CourseID, arg.Slug)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteScoresByCourse = `-- name: DeleteScoresByCourse :exec
DELETE FROM student_assessment_scores
WHERE registration_id IN (
    SELECT id FROM student_course_registrations WHERE course_id = $1
)
`

func (q *Queries) DeleteScoresByCourse(ctx context.Context, courseID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteScoresByCourse, courseID)
	return err
}

const getScoresByRegistration = `-- name: GetScoresByRegistration :many
SELECT id, registration_id, slug, score, is_absent, graded_by, graded_at FROM student_assessment_scores
WHERE registration_id = $1
ORDER BY graded_at
`

func (q *Queries) GetScoresByRegistration(ctx context.Context, registrationID uuid.UUID) ([]StudentAssessmentScore, error) {
	rows, err := q.db.Query(ctx, getScoresByRegistration, registrationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StudentAssessmentScore{}
	for rows.Next() {
		var i StudentAssessmentScore
		if err := rows.Scan(
			&i.ID,
			&i.RegistrationID,
			&i.Slug,
			&i.Score,
			&i.IsAbsent,
			&i.GradedBy,
			&i.GradedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAssessmentScore = `-- name: UpsertAssessmentScore :one
INSERT INTO student_assessment_scores (
    registration_id, slug, score, is_absent, graded_by, graded_at
) VALUES (
    $1, $2, $3, $4, $5, NOW()
)
ON CONFLICT (registration_id, slug) DO UPDATE SET
    score = EXCLUDED.score,
    is_absent = EXCLUDED.is_absent,
    graded_by = EXCLUDED.graded_by,
    graded_at = NOW()
RETURNING id, registration_id, slug, score, is_absent, graded_by, graded_at
`

type UpsertAssessmentScoreParams struct {
	RegistrationID uuid.UUID      `json:"registration_id"`
	Slug           string         `json:"slug"`
	Score          pgtype.Numeric `json:"score"`
	IsAbsent       pgtype.Bool    `json:"is_absent"`
	GradedBy       uuid.UUID      `json:"graded_by"`
}

func (q *Queries) UpsertAssessmentScore(ctx context.Context, arg UpsertAssessmentScoreParams) (StudentAssessmentScore, error) {
	row := q.db.QueryRow(ctx, upsertAssessmentScore,
		arg.RegistrationID,
		arg.Slug,
		arg.Score,
		arg.IsAbsent,
		arg.GradedBy,
	)
	var i StudentAssessmentScore
	err := row.Scan(
		&i.ID,
		&i.RegistrationID,
		&i.Slug,
		&i.Score,
		&i.IsAbsent,
		&i.GradedBy,
		&i.GradedAt,
	)
	return i, err
}
