// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForBulkInsertPrerequisiteCourses implements pgx.CopyFromSource.
type iteratorForBulkInsertPrerequisiteCourses struct {
	rows                 []BulkInsertPrerequisiteCoursesParams
	skippedFirstNextCall bool
}

func (r *iteratorForBulkInsertPrerequisiteCourses) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBulkInsertPrerequisiteCourses) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].CourseCode,
		r.rows[0].CourseID,
	}, nil
}

func (r iteratorForBulkInsertPrerequisiteCourses) Err() error {
	return nil
}

func (q *Queries) BulkInsertPrerequisiteCourses(ctx context.Context, arg []BulkInsertPrerequisiteCoursesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"prerequisite_courses_cache"}, []string{"course_code", "course_id"}, &iteratorForBulkInsertPrerequisiteCourses{rows: arg})
}
