// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: registrations.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countRegistrationsByCourse = `-- name: CountRegistrationsByCourse :one
SELECT COUNT(*) FROM student_course_registrations
WHERE course_id = $1
`

func (q *Queries) CountRegistrationsByCourse(ctx context.Context, courseID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRegistrationsByCourse, courseID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRegistration = `-- name: CreateRegistration :one
INSERT INTO student_course_registrations (
    student_id, course_id, semester, is_attendance_failed
) VALUES (
    $1, $2, $3, $4
)
ON CONFLICT (student_id, course_id) DO NOTHING
RETURNING id, student_id, course_id, semester, is_attendance_failed, created_at
`

type CreateRegistrationParams struct {
	StudentID          uuid.UUID   `json:"student_id"`
	CourseID           uuid.UUID   `json:"course_id"`
	Semester           string      `json:"semester"`
	IsAttendanceFailed pgtype.Bool `json:"is_attendance_failed"`
}

func (q *Queries) CreateRegistration(ctx context.Context, arg CreateRegistrationParams) (StudentCourseRegistration, error) {
	row := q.db.QueryRow(ctx, createRegistration,
		arg.StudentID,
		arg.CourseID,
		arg.Semester,
		arg.IsAttendanceFailed,
	)
	var i StudentCourseRegistration
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.CourseID,
		&i.Semester,
		&i.IsAttendanceFailed,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRegistrationsByCourse = `-- name: DeleteRegistrationsByCourse :exec
DELETE FROM student_course_registrations WHERE course_id = $1
`

func (q *Queries) DeleteRegistrationsByCourse(ctx context.Context, courseID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRegistrationsByCourse, courseID)
	return err
}

const getRegistrationByID = `-- name: GetRegistrationByID :one
SELECT
    r.id, r.student_id, r.course_id, r.semester, r.is_attendance_failed, r.created_at,
    s.student_number,
    s.first_name as student_first_name,
    s.last_name as student_last_name,
    s.department as student_department,
    c.course_code,
    c.course_name,
    c.instructor_id,
    c.assessment_schema
FROM student_course_registrations r
JOIN students_cache s ON r.student_id = s.id
JOIN courses_cache c ON r.course_id = c.id
WHERE r.id = $1
`

type GetRegistrationByIDRow struct {
	ID                 uuid.UUID        `json:"id"`
	StudentID          uuid.UUID        `json:"student_id"`
	CourseID           uuid.UUID        `json:"course_id"`
	Semester           string           `json:"semester"`
	IsAttendanceFailed pgtype.Bool      `json:"is_attendance_failed"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	StudentNumber      string           `json:"student_number"`
	StudentFirstName   pgtype.Text      `json:"student_first_name"`
	StudentLastName    pgtype.Text      `json:"student_last_name"`
	StudentDepartment  pgtype.Text      `json:"student_department"`
	CourseCode         string           `json:"course_code"`
	CourseName         string           `json:"course_name"`
	InstructorID       uuid.UUID        `json:"instructor_id"`
	AssessmentSchema   []byte           `json:"assessment_schema"`
}

func (q *Queries) GetRegistrationByID(ctx context.Context, id uuid.UUID) (GetRegistrationByIDRow, error) {
	row := q.db.QueryRow(ctx, getRegistrationByID, id)
	var i GetRegistrationByIDRow
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.CourseID,
		&i.Semester,
		&i.IsAttendanceFailed,
		&i.CreatedAt,
		&i.StudentNumber,
		&i.StudentFirstName,
		&i.StudentLastName,
		&i.StudentDepartment,
		&i.CourseCode,
		&i.CourseName,
		&i.InstructorID,
		&i.AssessmentSchema,
	)
	return i, err
}

const getRegistrationsByCourse = `-- name: GetRegistrationsByCourse :many
SELECT
    r.id, r.student_id, r.course_id, r.semester, r.is_attendance_failed, r.created_at,
    s.student_number,
    s.first_name as student_first_name,
    s.last_name as student_last_name,
    s.department as student_department
FROM student_course_registrations r
JOIN students_cache s ON r.student_id = s.id
WHERE r.course_id = $1
ORDER BY s.student_number
`

type GetRegistrationsByCourseRow struct {
	ID                 uuid.UUID        `json:"id"`
	StudentID          uuid.UUID        `json:"student_id"`
	CourseID           uuid.UUID        `json:"course_id"`
	Semester           string           `json:"semester"`
	IsAttendanceFailed pgtype.Bool      `json:"is_attendance_failed"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	StudentNumber      string           `json:"student_number"`
	StudentFirstName   pgtype.Text      `json:"student_first_name"`
	StudentLastName    pgtype.Text      `json:"student_last_name"`
	StudentDepartment  pgtype.Text      `json:"student_department"`
}

func (q *Queries) GetRegistrationsByCourse(ctx context.Context, courseID uuid.UUID) ([]GetRegistrationsByCourseRow, error) {
	rows, err := q.db.Query(ctx, getRegistrationsByCourse, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRegistrationsByCourseRow{}
	for rows.Next() {
		var i GetRegistrationsByCourseRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.CourseID,
			&i.Semester,
			&i.IsAttendanceFailed,
			&i.CreatedAt,
			&i.StudentNumber,
			&i.StudentFirstName,
			&i.StudentLastName,
			&i.StudentDepartment,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAttendanceFailed = `-- name: MarkAttendanceFailed :exec
UPDATE student_course_registrations
SET is_attendance_failed = true
WHERE student_id = $1 AND course_id = $2
`

type MarkAttendanceFailedParams struct {
	StudentID uuid.UUID `json:"student_id"`
	CourseID  uuid.UUID `json:"course_id"`
}

func (q *Queries) MarkAttendanceFailed(ctx context.Context, arg MarkAttendanceFailedParams) error {
	_, err := q.db.Exec(ctx, markAttendanceFailed, arg.StudentID, arg.CourseID)
	return err
}
