// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type CourseCatalogStatusEnum string

const (
	CourseCatalogStatusEnumActive          CourseCatalogStatusEnum = "active"
	CourseCatalogStatusEnumDraft           CourseCatalogStatusEnum = "draft"
	CourseCatalogStatusEnumPendingApproval CourseCatalogStatusEnum = "pending_approval"
	CourseCatalogStatusEnumUnderRevision   CourseCatalogStatusEnum = "under_revision"
	CourseCatalogStatusEnumArchived        CourseCatalogStatusEnum = "archived"
	CourseCatalogStatusEnumSuspended       CourseCatalogStatusEnum = "suspended"
)

func (e *CourseCatalogStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CourseCatalogStatusEnum(s)
	case string:
		*e = CourseCatalogStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for CourseCatalogStatusEnum: %T", src)
	}
	return nil
}

type NullCourseCatalogStatusEnum struct {
	CourseCatalogStatusEnum CourseCatalogStatusEnum `json:"course_catalog_status_enum"`
	Valid                   bool                    `json:"valid"` // Valid is true if CourseCatalogStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCourseCatalogStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.CourseCatalogStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CourseCatalogStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCourseCatalogStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CourseCatalogStatusEnum), nil
}

type CourseTypeEnum string

const (
	CourseTypeEnumMandatory CourseTypeEnum = "mandatory"
	CourseTypeEnumElective  CourseTypeEnum = "elective"
)

func (e *CourseTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CourseTypeEnum(s)
	case string:
		*e = CourseTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for CourseTypeEnum: %T", src)
	}
	return nil
}

type NullCourseTypeEnum struct {
	CourseTypeEnum CourseTypeEnum `json:"course_type_enum"`
	Valid          bool           `json:"valid"` // Valid is true if CourseTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCourseTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.CourseTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CourseTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCourseTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CourseTypeEnum), nil
}

type DayOfWeekEnum string

const (
	DayOfWeekEnumMonday    DayOfWeekEnum = "monday"
	DayOfWeekEnumTuesday   DayOfWeekEnum = "tuesday"
	DayOfWeekEnumWednesday DayOfWeekEnum = "wednesday"
	DayOfWeekEnumThursday  DayOfWeekEnum = "thursday"
	DayOfWeekEnumFriday    DayOfWeekEnum = "friday"
	DayOfWeekEnumSaturday  DayOfWeekEnum = "saturday"
	DayOfWeekEnumSunday    DayOfWeekEnum = "sunday"
)

func (e *DayOfWeekEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DayOfWeekEnum(s)
	case string:
		*e = DayOfWeekEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for DayOfWeekEnum: %T", src)
	}
	return nil
}

type NullDayOfWeekEnum struct {
	DayOfWeekEnum DayOfWeekEnum `json:"day_of_week_enum"`
	Valid         bool          `json:"valid"` // Valid is true if DayOfWeekEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDayOfWeekEnum) Scan(value interface{}) error {
	if value == nil {
		ns.DayOfWeekEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DayOfWeekEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDayOfWeekEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DayOfWeekEnum), nil
}

type OutboxStatusEnum string

const (
	OutboxStatusEnumPending   OutboxStatusEnum = "pending"
	OutboxStatusEnumProcessed OutboxStatusEnum = "processed"
	OutboxStatusEnumFailed    OutboxStatusEnum = "failed"
)

func (e *OutboxStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OutboxStatusEnum(s)
	case string:
		*e = OutboxStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for OutboxStatusEnum: %T", src)
	}
	return nil
}

type NullOutboxStatusEnum struct {
	OutboxStatusEnum OutboxStatusEnum `json:"outbox_status_enum"`
	Valid            bool             `json:"valid"` // Valid is true if OutboxStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOutboxStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.OutboxStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OutboxStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOutboxStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OutboxStatusEnum), nil
}

type CourseCatalog struct {
	ID               pgtype.UUID                 `json:"id"`
	CourseCode       string                      `json:"course_code"`
	Name             string                      `json:"name"`
	Faculty          string                      `json:"faculty"`
	Department       string                      `json:"department"`
	ClassLevel       int16                       `json:"class_level"`
	Credits          int16                       `json:"credits"`
	TheoreticalHours int16                       `json:"theoretical_hours"`
	PracticalHours   int16                       `json:"practical_hours"`
	CourseType       CourseTypeEnum              `json:"course_type"`
	Prerequisites    []byte                      `json:"prerequisites"`
	Description      pgtype.Text                 `json:"description"`
	LearningOutcomes pgtype.Text                 `json:"learning_outcomes"`
	Syllabus         pgtype.Text                 `json:"syllabus"`
	Status           NullCourseCatalogStatusEnum `json:"status"`
	CreatedAt        pgtype.Timestamp            `json:"created_at"`
	UpdatedAt        pgtype.Timestamp            `json:"updated_at"`
}

type CourseScheduleSession struct {
	ID               pgtype.UUID      `json:"id"`
	SemesterCourseID pgtype.UUID      `json:"semester_course_id"`
	DayOfWeek        DayOfWeekEnum    `json:"day_of_week"`
	SlotNumber       int16            `json:"slot_number"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
}

type OutboxEvent struct {
	ID           pgtype.UUID          `json:"id"`
	EventType    string               `json:"event_type"`
	RoutingKey   string               `json:"routing_key"`
	Payload      []byte               `json:"payload"`
	Status       NullOutboxStatusEnum `json:"status"`
	RetryCount   pgtype.Int2          `json:"retry_count"`
	MaxRetries   pgtype.Int2          `json:"max_retries"`
	CreatedAt    pgtype.Timestamp     `json:"created_at"`
	ProcessedAt  pgtype.Timestamp     `json:"processed_at"`
	ErrorMessage pgtype.Text          `json:"error_message"`
}

type SemesterCourse struct {
	ID                 pgtype.UUID      `json:"id"`
	Semester           string           `json:"semester"`
	CourseCode         string           `json:"course_code"`
	Credits            int16            `json:"credits"`
	ClassLevel         int16            `json:"class_level"`
	InstructorID       pgtype.UUID      `json:"instructor_id"`
	InstructorFullname string           `json:"instructor_fullname"`
	ClassroomLocation  string           `json:"classroom_location"`
	MaxCapacity        int16            `json:"max_capacity"`
	AssessmentSchema   []byte           `json:"assessment_schema"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
	// Snapshot of course prerequisites at the time of semester course creation. Format: [{"course_code":"MAT101","min_grade":60}]
	Prerequisites []byte `json:"prerequisites"`
}
