// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: schedule.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkInstructorScheduleConflict = `-- name: CheckInstructorScheduleConflict :many
SELECT sc.course_code, sc.id
FROM course_schedule_sessions css
JOIN semester_courses sc ON css.semester_course_id = sc.id
WHERE css.day_of_week = ANY($1::day_of_week_enum[])
  AND css.slot_number = ANY($2::SMALLINT[])
  AND sc.semester = $3
  AND sc.instructor_id = $4
  AND sc.id != $5
`

type CheckInstructorScheduleConflictParams struct {
	Days            []DayOfWeekEnum `json:"days"`
	Slots           []int16         `json:"slots"`
	Semester        string          `json:"semester"`
	InstructorID    pgtype.UUID     `json:"instructor_id"`
	ExcludeCourseID pgtype.UUID     `json:"exclude_course_id"`
}

type CheckInstructorScheduleConflictRow struct {
	CourseCode string      `json:"course_code"`
	ID         pgtype.UUID `json:"id"`
}

func (q *Queries) CheckInstructorScheduleConflict(ctx context.Context, arg CheckInstructorScheduleConflictParams) ([]CheckInstructorScheduleConflictRow, error) {
	rows, err := q.db.Query(ctx, checkInstructorScheduleConflict,
		arg.Days,
		arg.Slots,
		arg.Semester,
		arg.InstructorID,
		arg.ExcludeCourseID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CheckInstructorScheduleConflictRow{}
	for rows.Next() {
		var i CheckInstructorScheduleConflictRow
		if err := rows.Scan(&i.CourseCode, &i.ID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createScheduleSession = `-- name: CreateScheduleSession :one
INSERT INTO course_schedule_sessions (semester_course_id, day_of_week, slot_number)
VALUES ($1, $2, $3)
RETURNING id, semester_course_id, day_of_week, slot_number, created_at
`

type CreateScheduleSessionParams struct {
	SemesterCourseID pgtype.UUID   `json:"semester_course_id"`
	DayOfWeek        DayOfWeekEnum `json:"day_of_week"`
	SlotNumber       int16         `json:"slot_number"`
}

func (q *Queries) CreateScheduleSession(ctx context.Context, arg CreateScheduleSessionParams) (CourseScheduleSession, error) {
	row := q.db.QueryRow(ctx, createScheduleSession, arg.SemesterCourseID, arg.DayOfWeek, arg.SlotNumber)
	var i CourseScheduleSession
	err := row.Scan(
		&i.ID,
		&i.SemesterCourseID,
		&i.DayOfWeek,
		&i.SlotNumber,
		&i.CreatedAt,
	)
	return i, err
}

const deleteScheduleSessionsByCourseID = `-- name: DeleteScheduleSessionsByCourseID :exec
DELETE FROM course_schedule_sessions
WHERE semester_course_id = $1
`

func (q *Queries) DeleteScheduleSessionsByCourseID(ctx context.Context, semesterCourseID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteScheduleSessionsByCourseID, semesterCourseID)
	return err
}

const getScheduleSessionsByCourseID = `-- name: GetScheduleSessionsByCourseID :many
SELECT id, semester_course_id, day_of_week, slot_number, created_at
FROM course_schedule_sessions
WHERE semester_course_id = $1
ORDER BY day_of_week, slot_number
`

func (q *Queries) GetScheduleSessionsByCourseID(ctx context.Context, semesterCourseID pgtype.UUID) ([]CourseScheduleSession, error) {
	rows, err := q.db.Query(ctx, getScheduleSessionsByCourseID, semesterCourseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CourseScheduleSession{}
	for rows.Next() {
		var i CourseScheduleSession
		if err := rows.Scan(
			&i.ID,
			&i.SemesterCourseID,
			&i.DayOfWeek,
			&i.SlotNumber,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScheduleSessionsByMultipleCourseIDs = `-- name: GetScheduleSessionsByMultipleCourseIDs :many
SELECT id, semester_course_id, day_of_week, slot_number, created_at
FROM course_schedule_sessions
WHERE semester_course_id = ANY($1::UUID[])
ORDER BY semester_course_id, day_of_week, slot_number
`

func (q *Queries) GetScheduleSessionsByMultipleCourseIDs(ctx context.Context, courseIds []pgtype.UUID) ([]CourseScheduleSession, error) {
	rows, err := q.db.Query(ctx, getScheduleSessionsByMultipleCourseIDs, courseIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CourseScheduleSession{}
	for rows.Next() {
		var i CourseScheduleSession
		if err := rows.Scan(
			&i.ID,
			&i.SemesterCourseID,
			&i.DayOfWeek,
			&i.SlotNumber,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
