// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attendance_records.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkAttendanceExists = `-- name: CheckAttendanceExists :one
SELECT COUNT(*) as count
FROM attendance_records
WHERE session_id = $1 AND student_id = $2
`

type CheckAttendanceExistsParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	StudentID pgtype.UUID `json:"student_id"`
}

func (q *Queries) CheckAttendanceExists(ctx context.Context, arg CheckAttendanceExistsParams) (int64, error) {
	row := q.db.QueryRow(ctx, checkAttendanceExists, arg.SessionID, arg.StudentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAttendanceRecordManual = `-- name: CreateAttendanceRecordManual :one
INSERT INTO attendance_records (
    session_id, student_id, course_id, semester, week_number,
    is_present, marked_via, manually_marked_by, manually_marked_at, manual_note
) VALUES (
    $1, $2, $3, $4, $5, $6, 'manual', $7, NOW(), $8
) ON CONFLICT (session_id, student_id)
DO UPDATE SET
    is_present = EXCLUDED.is_present,
    marked_via = EXCLUDED.marked_via,
    manually_marked_by = EXCLUDED.manually_marked_by,
    manually_marked_at = NOW(),
    manual_note = EXCLUDED.manual_note
RETURNING id, session_id, student_id, course_id, semester, week_number, is_present, marked_via, scanned_at, qr_timestamp, manually_marked_by, manually_marked_at, manual_note, created_at
`

type CreateAttendanceRecordManualParams struct {
	SessionID        pgtype.UUID `json:"session_id"`
	StudentID        pgtype.UUID `json:"student_id"`
	CourseID         pgtype.UUID `json:"course_id"`
	Semester         string      `json:"semester"`
	WeekNumber       int16       `json:"week_number"`
	IsPresent        bool        `json:"is_present"`
	ManuallyMarkedBy pgtype.UUID `json:"manually_marked_by"`
	ManualNote       pgtype.Text `json:"manual_note"`
}

func (q *Queries) CreateAttendanceRecordManual(ctx context.Context, arg CreateAttendanceRecordManualParams) (AttendanceRecord, error) {
	row := q.db.QueryRow(ctx, createAttendanceRecordManual,
		arg.SessionID,
		arg.StudentID,
		arg.CourseID,
		arg.Semester,
		arg.WeekNumber,
		arg.IsPresent,
		arg.ManuallyMarkedBy,
		arg.ManualNote,
	)
	var i AttendanceRecord
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.StudentID,
		&i.CourseID,
		&i.Semester,
		&i.WeekNumber,
		&i.IsPresent,
		&i.MarkedVia,
		&i.ScannedAt,
		&i.QrTimestamp,
		&i.ManuallyMarkedBy,
		&i.ManuallyMarkedAt,
		&i.ManualNote,
		&i.CreatedAt,
	)
	return i, err
}

const createAttendanceRecordQR = `-- name: CreateAttendanceRecordQR :exec
INSERT INTO attendance_records (
    session_id, student_id, course_id, semester, week_number,
    is_present, marked_via, scanned_at, qr_timestamp
) VALUES (
    $1, $2, $3, $4, $5, TRUE, 'qr_scan', $6, $7
) ON CONFLICT (session_id, student_id) DO NOTHING
`

type CreateAttendanceRecordQRParams struct {
	SessionID   pgtype.UUID      `json:"session_id"`
	StudentID   pgtype.UUID      `json:"student_id"`
	CourseID    pgtype.UUID      `json:"course_id"`
	Semester    string           `json:"semester"`
	WeekNumber  int16            `json:"week_number"`
	ScannedAt   pgtype.Timestamp `json:"scanned_at"`
	QrTimestamp pgtype.Int8      `json:"qr_timestamp"`
}

func (q *Queries) CreateAttendanceRecordQR(ctx context.Context, arg CreateAttendanceRecordQRParams) error {
	_, err := q.db.Exec(ctx, createAttendanceRecordQR,
		arg.SessionID,
		arg.StudentID,
		arg.CourseID,
		arg.Semester,
		arg.WeekNumber,
		arg.ScannedAt,
		arg.QrTimestamp,
	)
	return err
}

const getAttendanceRecordsBySession = `-- name: GetAttendanceRecordsBySession :many
SELECT
    ar.id,
    ar.session_id,
    ar.student_id,
    ar.course_id,
    ar.semester,
    ar.week_number,
    ar.is_present,
    ar.marked_via,
    ar.scanned_at,
    ar.qr_timestamp,
    ar.manually_marked_by,
    ar.manually_marked_at as marked_at,
    ar.manual_note,
    ar.created_at
FROM attendance_records ar
WHERE ar.session_id = $1
ORDER BY ar.created_at DESC
`

type GetAttendanceRecordsBySessionRow struct {
	ID               pgtype.UUID      `json:"id"`
	SessionID        pgtype.UUID      `json:"session_id"`
	StudentID        pgtype.UUID      `json:"student_id"`
	CourseID         pgtype.UUID      `json:"course_id"`
	Semester         string           `json:"semester"`
	WeekNumber       int16            `json:"week_number"`
	IsPresent        bool             `json:"is_present"`
	MarkedVia        string           `json:"marked_via"`
	ScannedAt        pgtype.Timestamp `json:"scanned_at"`
	QrTimestamp      pgtype.Int8      `json:"qr_timestamp"`
	ManuallyMarkedBy pgtype.UUID      `json:"manually_marked_by"`
	MarkedAt         pgtype.Timestamp `json:"marked_at"`
	ManualNote       pgtype.Text      `json:"manual_note"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) GetAttendanceRecordsBySession(ctx context.Context, sessionID pgtype.UUID) ([]GetAttendanceRecordsBySessionRow, error) {
	rows, err := q.db.Query(ctx, getAttendanceRecordsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAttendanceRecordsBySessionRow{}
	for rows.Next() {
		var i GetAttendanceRecordsBySessionRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.StudentID,
			&i.CourseID,
			&i.Semester,
			&i.WeekNumber,
			&i.IsPresent,
			&i.MarkedVia,
			&i.ScannedAt,
			&i.QrTimestamp,
			&i.ManuallyMarkedBy,
			&i.MarkedAt,
			&i.ManualNote,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCourseAttendanceStats = `-- name: GetCourseAttendanceStats :many
SELECT
    s.id as student_id,
    s.student_number,
    s.first_name,
    s.last_name,
    COUNT(*) FILTER (WHERE ar.is_present = TRUE) as present_count,
    COUNT(*) FILTER (WHERE ar.is_present = FALSE) as absent_count,
    ARRAY_AGG(ar.week_number ORDER BY ar.week_number) FILTER (WHERE ar.is_present = FALSE) as absent_weeks
FROM enrollments_cache e
JOIN students_cache s ON e.student_id = s.id
LEFT JOIN attendance_records ar ON ar.student_id = s.id AND ar.course_id = e.course_id
WHERE e.course_id = $1 AND e.semester = $2
GROUP BY s.id, s.student_number, s.first_name, s.last_name
ORDER BY s.student_number
`

type GetCourseAttendanceStatsParams struct {
	CourseID pgtype.UUID `json:"course_id"`
	Semester string      `json:"semester"`
}

type GetCourseAttendanceStatsRow struct {
	StudentID     pgtype.UUID `json:"student_id"`
	StudentNumber string      `json:"student_number"`
	FirstName     pgtype.Text `json:"first_name"`
	LastName      pgtype.Text `json:"last_name"`
	PresentCount  int64       `json:"present_count"`
	AbsentCount   int64       `json:"absent_count"`
	AbsentWeeks   interface{} `json:"absent_weeks"`
}

func (q *Queries) GetCourseAttendanceStats(ctx context.Context, arg GetCourseAttendanceStatsParams) ([]GetCourseAttendanceStatsRow, error) {
	rows, err := q.db.Query(ctx, getCourseAttendanceStats, arg.CourseID, arg.Semester)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCourseAttendanceStatsRow{}
	for rows.Next() {
		var i GetCourseAttendanceStatsRow
		if err := rows.Scan(
			&i.StudentID,
			&i.StudentNumber,
			&i.FirstName,
			&i.LastName,
			&i.PresentCount,
			&i.AbsentCount,
			&i.AbsentWeeks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFailingStudentsByCourse = `-- name: GetFailingStudentsByCourse :many
SELECT
    s.id as student_id,
    s.student_number,
    s.first_name,
    s.last_name,
    s.email,
    COUNT(*) FILTER (WHERE ar.is_present = TRUE) as present_count,
    COUNT(*) FILTER (WHERE ar.is_present = FALSE) as absent_count
FROM enrollments_cache e
JOIN students_cache s ON e.student_id = s.id
LEFT JOIN attendance_records ar ON ar.student_id = s.id AND ar.course_id = e.course_id AND ar.semester = e.semester
WHERE e.course_id = $1 AND e.semester = $2
GROUP BY s.id, s.student_number, s.first_name, s.last_name, s.email
HAVING COUNT(*) FILTER (WHERE ar.is_present = FALSE) >= 4
`

type GetFailingStudentsByCourseParams struct {
	CourseID pgtype.UUID `json:"course_id"`
	Semester string      `json:"semester"`
}

type GetFailingStudentsByCourseRow struct {
	StudentID     pgtype.UUID `json:"student_id"`
	StudentNumber string      `json:"student_number"`
	FirstName     pgtype.Text `json:"first_name"`
	LastName      pgtype.Text `json:"last_name"`
	Email         pgtype.Text `json:"email"`
	PresentCount  int64       `json:"present_count"`
	AbsentCount   int64       `json:"absent_count"`
}

func (q *Queries) GetFailingStudentsByCourse(ctx context.Context, arg GetFailingStudentsByCourseParams) ([]GetFailingStudentsByCourseRow, error) {
	rows, err := q.db.Query(ctx, getFailingStudentsByCourse, arg.CourseID, arg.Semester)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFailingStudentsByCourseRow{}
	for rows.Next() {
		var i GetFailingStudentsByCourseRow
		if err := rows.Scan(
			&i.StudentID,
			&i.StudentNumber,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.PresentCount,
			&i.AbsentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMarkedStudentsBySession = `-- name: GetMarkedStudentsBySession :many
SELECT student_id
FROM attendance_records
WHERE session_id = $1
`

func (q *Queries) GetMarkedStudentsBySession(ctx context.Context, sessionID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getMarkedStudentsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var student_id pgtype.UUID
		if err := rows.Scan(&student_id); err != nil {
			return nil, err
		}
		items = append(items, student_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionAttendanceCounts = `-- name: GetSessionAttendanceCounts :one
SELECT
    COUNT(*) FILTER (WHERE is_present = TRUE) as present_count,
    COUNT(*) FILTER (WHERE is_present = FALSE) as absent_count
FROM attendance_records
WHERE session_id = $1
`

type GetSessionAttendanceCountsRow struct {
	PresentCount int64 `json:"present_count"`
	AbsentCount  int64 `json:"absent_count"`
}

func (q *Queries) GetSessionAttendanceCounts(ctx context.Context, sessionID pgtype.UUID) (GetSessionAttendanceCountsRow, error) {
	row := q.db.QueryRow(ctx, getSessionAttendanceCounts, sessionID)
	var i GetSessionAttendanceCountsRow
	err := row.Scan(&i.PresentCount, &i.AbsentCount)
	return i, err
}

const getStudentAttendanceByCourse = `-- name: GetStudentAttendanceByCourse :many
SELECT
    ar.week_number,
    ats.session_date,
    ar.is_present,
    ar.marked_via,
    ar.manual_note,
    ar.scanned_at,
    ar.manually_marked_at
FROM attendance_records ar
JOIN attendance_sessions ats ON ar.session_id = ats.id
WHERE ar.student_id = $1 AND ar.course_id = $2 AND ar.semester = $3
ORDER BY ar.week_number ASC
`

type GetStudentAttendanceByCourseParams struct {
	StudentID pgtype.UUID `json:"student_id"`
	CourseID  pgtype.UUID `json:"course_id"`
	Semester  string      `json:"semester"`
}

type GetStudentAttendanceByCourseRow struct {
	WeekNumber       int16            `json:"week_number"`
	SessionDate      pgtype.Date      `json:"session_date"`
	IsPresent        bool             `json:"is_present"`
	MarkedVia        string           `json:"marked_via"`
	ManualNote       pgtype.Text      `json:"manual_note"`
	ScannedAt        pgtype.Timestamp `json:"scanned_at"`
	ManuallyMarkedAt pgtype.Timestamp `json:"manually_marked_at"`
}

func (q *Queries) GetStudentAttendanceByCourse(ctx context.Context, arg GetStudentAttendanceByCourseParams) ([]GetStudentAttendanceByCourseRow, error) {
	rows, err := q.db.Query(ctx, getStudentAttendanceByCourse, arg.StudentID, arg.CourseID, arg.Semester)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStudentAttendanceByCourseRow{}
	for rows.Next() {
		var i GetStudentAttendanceByCourseRow
		if err := rows.Scan(
			&i.WeekNumber,
			&i.SessionDate,
			&i.IsPresent,
			&i.MarkedVia,
			&i.ManualNote,
			&i.ScannedAt,
			&i.ManuallyMarkedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
